### ISSUE TITLE
Notification body format documentation needs updating

### ISSUE THREAD

**Issue by charlesverge** [trycourier/courier-android#13]
Documentation is needed for what is supported on the android platform for firebase messages in https://github.com/trycourier/courier-android/blob/master/Docs/PushNotifications.md

In the ui there is options to add
1. Text
2. Image
3. Action block
4. Markdown block
5. Quote block
6. List

I could not locate any specific documentation on which of these are supported and how to handle the ones that do produce data. For example
1. Sdk does not handle images
2. Action block appears to have a tracking url provided but it is not clear how to follow that link
3. Markdown block is sent but not handled
4. Quote block is formatted as plain text
5. List appears to be not sent in the data package

On the Android platform.

In the provided presentNotification these are all handled as text and some are not supported.
https://github.com/trycourier/courier-android/blob/master/android/src/main/java/com/courier/android/notifications/RemoteMessageExtensions.kt

In the data provided as shown by a debug log of the message data the 
11-14 04:02:28.646 16777 16819 D Notifications: {body=This is a second text block
11-14 04:02:28.646 16777 16819 D Notifications: https://backend-production-librarybucket-1izigk5lryla9.s3.amazonaws.com/c3bb393e-c439-4e8e-83f2-fa2c794c0ba4/1699901479608_test-sum.png
11-14 04:02:28.646 16777 16819 D Notifications: Click Here: https://c3bb393e-c439-4e8e-83f2-fa2c794c0ba4-test.ct0.app/r/btn608y0hkmqabn3vc7f9k0kcm8k
11-14 04:02:28.646 16777 16819 D Notifications: ---
11-14 04:02:28.646 16777 16819 D Notifications: New to Markdown? Get started [here](http://daringfireball.net/projects/markdown/).
11-14 04:02:28.646 16777 16819 D Notifications: "Cras lacinia elit fringilla consequat placerat...", title=This is a test message, trackingUrl=https://c3bb393e-c439-4e8e-83f2-fa2c794c0ba4-test.ct0.app/t/955c0xhzp1mn8dnmnevtf8esthaq}

**Screenshots**

Design:
![image](https://github.com/trycourier/courier-android/assets/1906614/326480a4-3f02-4ed6-a139-25620cad026a)

Preview
![image](https://github.com/trycourier/courier-android/assets/1906614/f80c11a0-450e-48bd-a1a7-7a081f67cbcf)

Notification preview on phone
![image](https://github.com/trycourier/courier-android/assets/1906614/df28aab9-f5b8-4b4a-b5c2-a67a4fafc167)

**Comment by mikemilla** [comment]
Hey @charlesverge, I know it's late, but we've noted these and are working on polishing all these up. The issue is in how our backend renders the messages and we have lots of changes coming to support this as well as make it work better with our template designer.

Thank you for testing <3
