### ISSUE TITLE
No Courier proguard rules defined in docs or AAR

### ISSUE THREAD

**Issue by lance0428** [trycourier/courier-android#14]
Our app uses proguard to obfuscate and minimize. Our recent Courier integration works for non-proguarded builds but fails w/ the following error when it is proguarded.

```
21:10:44.513  D  Courier set push token failed
                 com.courier.android.models.CourierException: null: null
                 	at A3.k.a(CourierServerError.kt:5)
                 	at com.courier.android.repositories.g.onResponse(ServiceExtensions.kt:81)
                 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:53)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
```

I was able to workaround the problem by adding the following to our app's proguard config

```
# Courier
-keep class com.courier.** { *; }
```

Above is a bit of a sledgehammer approach to defining proguard rules. It would be nice if you all defined in a more granular way the exact config needed to maximize obfuscation and minimization yet still function as intended.

At a minimum whatever the rules are should be documented in the README docs. Ideally it would be auto-configured via your library using technique documented under the _'A library module might include its own ProGuard configuration file.'_ section of [these docs](https://developer.android.com/studio/projects/android-library#Considerations) so the consumers of the SDK don't even need to worry about it.

**Comment by mikemilla** [comment]
@lance0428 looking at bundling this in the SDK: https://github.com/trycourier/courier-android/blob/feature/polish-07012024/android/consumer-rules.pro

This would basically keep all of the SDK as is, but feedback is very much appreciated here. Would this cover what you are looking for or do you have any other ideas?

**Comment by mikemilla** [comment]
Automatic proguard rules are merged into master. Please let us know if you have other issues or have suggested changes: https://github.com/trycourier/courier-android/blob/master/android/consumer-rules.pro

@lance0428
