### ISSUE TITLE
Latest Versions of the SDK are not available on Jitpack

### ISSUE THREAD

**Issue by muratke** [trycourier/courier-android#16]
Latest versions of the SDK (3.5.1 ... 3.5.10) are not available on Jitpack.

<img width="612" alt="Screenshot 2024-07-08 at 5 28 37 PM" src="https://github.com/trycourier/courier-android/assets/16153291/547d2d7d-93f9-40f3-b8b6-f34a8385dc8f">

<img width="587" alt="Screenshot 2024-07-08 at 5 31 35 PM" src="https://github.com/trycourier/courier-android/assets/16153291/f33a5d28-1eba-401c-8c0e-9786a7ce23fb">

**Comment by mikemilla** [comment]
@muratke thanks for the callout. The build is available, but there are import issues. Working on fixing that now!

**Comment by mikemilla** [comment]
@muratke fix is live for this in `3.5.13`. Thank you for reporting!
