### ISSUE TITLE
Manual Notification Tracking Documentation is not up-to-date

### ISSUE THREAD

**Issue by muratke** [trycourier/courier-android#17]
[Manual Notification Tracking Documentation](https://github.com/trycourier/courier-android/blob/master/Docs/PushNotifications.md#manual-notification-tracking) is still for the version 3 of the SDK, the API has been changed but documentation not updated.

**Comment by mikemilla** [comment]
Thanks @muratke. Docs are updated.

Here is what you need to use:

```
lifecycleScope.launch {

    val client = Courier.shared.client // or use CourierClient(...)

    client.tracking.postTrackingUrl(
        url = "https://courier.com/your_tracking_url",
        event = CourierTrackingEvent.CLICKED,
    )

}
```
